- name: Configuring syslog-ng server
  copy:
    src: syslog-ng.conf
    dest: /etc/syslog-ng/syslog-ng.conf
  notify:
    - restart syslog-ng
- name: Configuring journalctl
  template:
    src: journald.j2
    dest: /etc/systemd/journald.conf
  notify:
    - restart systemd-journald
    - restart syslog-ng
