---
- name: enable additional software channels
  redhat_repositories:
    id:
      - rhel-7-server-eus-optional-rpms
    state: enabled
- name: install syslog-ng server
  yum:
    name: syslog-ng
    state: present
- name: configuring syslog-ng server
  copy:
    src: syslog-ng.conf
    dest: /etc/syslog-ng/syslog-ng.conf
  notify:
    - restart syslog-ng
- name: configuring journalctl
  template:
    src: journald.j2
    dest: /etc/systemd/journald.conf
  notify:
    - restart systemd-journald
    - restart syslog-ng
